spring.application.name=fitness

jwt.secret=meinSuperGeheimerKeyDenNiemandKnackt0123456789
jwt.expiration=86400000
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:fitness